services:
  - type: web
    name: identity-service
    env: docker
    dockerfilePath: ./src/Services/IdentityService/Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: "Server=ep-wild-violet-ad4xn118-pooler.c-2.us-east-1.aws.neon.tech;Database=neondb;User Id=neondb_owner;Password=npg_7OByscUPiGM0;Ssl Mode=Require;"

  - type: web
    name: inventory-service
    env: docker
    dockerfilePath: ./src/Services/InventoryService/Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: "Server=ep-wild-violet-ad4xn118-pooler.c-2.us-east-1.aws.neon.tech;Database=neondb;User Id=neondb_owner;Password=npg_7OByscUPiGM0;Ssl Mode=Require;"

  - type: web
    name: order-service
    env: docker
    dockerfilePath: ./src/Services/OrderService/Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: "Server=ep-wild-violet-ad4xn118-pooler.c-2.us-east-1.aws.neon.tech;Database=neondb;User Id=neondb_owner;Password=npg_7OByscUPiGM0;Ssl Mode=Require;"
      - key: ConnectionStrings__PosConnection
        value: "Server=ep-wild-violet-ad4xn118-pooler.c-2.us-east-1.aws.neon.tech;Database=neondb;User Id=neondb_owner;Password=npg_7OByscUPiGM0;Ssl Mode=Require;"

  - type: web
    name: transaction-service
    env: docker
    dockerfilePath: ./src/Services/TransactionService/Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: "Server=ep-wild-violet-ad4xn118-pooler.c-2.us-east-1.aws.neon.tech;Database=neondb;User Id=neondb_owner;Password=npg_7OByscUPiGM0;Ssl Mode=Require;"

  - type: web
    name: api-gateway
    env: docker
    dockerfilePath: ./src/ApiGateway/Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: ReverseProxy__Clusters__auth-cluster__Destinations__destination1__Address
        value: "http://identity-service:5101"
      - key: ReverseProxy__Clusters__inventory-cluster__Destinations__destination1__Address
        value: "http://inventory-service:5102"
      - key: ReverseProxy__Clusters__orders-cluster__Destinations__destination1__Address
        value: "http://order-service:5105"
      - key: ReverseProxy__Clusters__transactions-cluster__Destinations__destination1__Address
        value: "http://transaction-service:5103"
